# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html for details

[[override]]
  name = "istio.io/api"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "istio.io/istio"
  version = "1.1.0"

[[constraint]]
  name = "github.com/3scale/3scale-go-client"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/3scale/3scale-porta-go-client"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    # This is required since we need some yaml from the mixers testdata
    # We could remove the build flag with the integration tag from our own integration test but prefer to have that isolated
    # since the integration test framework will also likely be isolated goiung forward, validating this workaround.
    name = "istio.io/istio"
    non-go = false
    unused-packages = false
