apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 3scale-istio-adapter
  name: 3scale-istio-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3scale-istio-adapter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: 3scale-istio-adapter
    spec:
      containers:
      - image: quay.io/3scale/3scale-istio-adapter:v0.5.0
        imagePullPolicy: Always
        name: 3scale-istio-adapter
        ports:
        - containerPort: 3333
          protocol: TCP
          name: adapter
        - containerPort: 8080
          protocol: TCP
          name: prometheus
        livenessProbe:
          tcpSocket:
            port: 3333
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: "THREESCALE_LOG_JSON"
          value: "true"
        - name: "THREESCALE_REPORT_METRICS"
          value: "true"
        - name: "THREESCALE_METRICS_PORT"
          value: "8080"
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

